"""create initial database schema

Revision ID: 7beff164eaa0
Revises: 
Create Date: 2026-09-01 17:06:18.746840

"""
from typing import Sequence, Union
import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7beff164eaa0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('username', sa.String(
                        length=100), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('username')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('blogs',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=False),
                    sa.Column('topic', sa.Text(), nullable=False),
                    sa.Column('target_audience', sa.Text(), nullable=False),
                    sa.Column('content_type', sa.Text(), nullable=False),
                    sa.Column('desired_length', sa.Integer(), nullable=False),
                    sa.Column('tone', sa.Text(), nullable=False),
                    sa.Column('additional_instructions',
                              sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_blogs_user_id'), 'blogs',
                    ['user_id'], unique=False)
    op.create_table('drafts',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('blog_id', sa.UUID(), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('content', sa.Text(), nullable=True),
                    sa.Column('status', sa.String(length=50), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['blog_id'], ['blogs.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_drafts_blog_id'),
                    'drafts', ['blog_id'], unique=False)
    op.create_table('research',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('blog_id', sa.UUID(), nullable=False),
                    sa.Column('research_summary', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['blog_id'], ['blogs.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_research_blog_id'),
                    'research', ['blog_id'], unique=True)
    op.create_table('research_sources',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('research_id', sa.UUID(), nullable=False),
                    sa.Column('source_id', sa.String(
                        length=255), nullable=False),
                    sa.Column('title', sa.Text(), nullable=False),
                    sa.Column('url', sa.Text(), nullable=False),
                    sa.Column('domain', sa.String(length=255), nullable=False),
                    sa.Column('snippet', sa.Text(), nullable=True),
                    sa.Column('published_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('retrieved_at', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('selection_reason', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['research_id'], ['research.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_research_sources_research_id'),
                    'research_sources', ['research_id'], unique=False)
    op.create_index(op.f('ix_research_sources_source_id'),
                    'research_sources', ['source_id'], unique=False)
    op.create_table('research_chunks',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('research_id', sa.UUID(), nullable=False),
                    sa.Column('research_source_id', sa.UUID(), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('chunk_index', sa.Integer(), nullable=False),
                    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(
                        dim=384), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['research_id'], ['research.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['research_source_id'], [
                        'research_sources.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_research_chunks_research_id'),
                    'research_chunks', ['research_id'], unique=False)
    op.create_index(op.f('ix_research_chunks_research_source_id'),
                    'research_chunks', ['research_source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_chunks_research_source_id'),
                  table_name='research_chunks')
    op.drop_index(op.f('ix_research_chunks_research_id'),
                  table_name='research_chunks')
    op.drop_table('research_chunks')
    op.drop_index(op.f('ix_research_sources_source_id'),
                  table_name='research_sources')
    op.drop_index(op.f('ix_research_sources_research_id'),
                  table_name='research_sources')
    op.drop_table('research_sources')
    op.drop_index(op.f('ix_research_blog_id'), table_name='research')
    op.drop_table('research')
    op.drop_index(op.f('ix_drafts_blog_id'), table_name='drafts')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_blogs_user_id'), table_name='blogs')
    op.drop_table('blogs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
