"""initial migration

Revision ID: be9631034d8e
Revises: 
Create Date: 2026-09-02 15:40:34.531183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'be9631034d8e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('research_sources',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('research_id', sa.UUID(), nullable=False),
                    sa.Column('source_id', sa.String(
                        length=255), nullable=False),
                    sa.Column('title', sa.Text(), nullable=False),
                    sa.Column('url', sa.Text(), nullable=False),
                    sa.Column('selection_reason', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['research_id'], ['research.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_research_sources_research_id'),
                    'research_sources', ['research_id'], unique=False)
    op.create_index(op.f('ix_research_sources_source_id'),
                    'research_sources', ['source_id'], unique=False)
    op.create_table('research_chunks',
                    sa.Column('id', sa.UUID(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.Column('research_id', sa.UUID(), nullable=False),
                    sa.Column('research_source_id', sa.UUID(), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('chunk_index', sa.Integer(), nullable=False),
                    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(
                        dim=384), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['research_id'], ['research.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['research_source_id'], [
                        'research_sources.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_research_chunks_research_id'),
                    'research_chunks', ['research_id'], unique=False)
    op.create_index(op.f('ix_research_chunks_research_source_id'),
                    'research_chunks', ['research_source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_chunks_research_source_id'),
                  table_name='research_chunks')
    op.drop_index(op.f('ix_research_chunks_research_id'),
                  table_name='research_chunks')
    op.drop_table('research_chunks')
    op.drop_index(op.f('ix_research_sources_source_id'),
                  table_name='research_sources')
    op.drop_index(op.f('ix_research_sources_research_id'),
                  table_name='research_sources')
    op.drop_table('research_sources')
    op.drop_table('research')
    # ### end Alembic commands ###
