from enum import Enum


class ErrorCodes(str, Enum):

    RESEARCH_SEARCH_FAILED = "RESEARCH_SEARCH_FAILED"
    RESEARCH_EXTRACTION_FAILED = "RESEARCH_EXTRACTION_FAILED"
    RESEARCH_GENERATION_FAILED = 'RESEARCH_GENERATION_FAILED'
    RESEARCH_PERSISTENCE_FAILED = "RESEARCH_PERSISTENCE_FAILED"

    ANALYSIS_RETRIEVAL_FAILED = "ANALYSIS_RETRIEVAL_FAILED"
    ANALYSIS_GENERATION_FAILED = "ANALYSIS_GENERATION_FAILED"
    ANALYSIS_PERSISTENCE_FAILED = "ANALYSIS_PERSISTENCE_FAILED"

    FACT_CHECK_RETRIEVAL_FAILED = "FACT_CHECK_RETRIEVAL_FAILED"
    FACT_CHECK_GENERATION_FAILED = "FACT_CHECK_GENERATION_FAILED"
    FACT_CHECK_PERSISTENCE_FAILED = "FACT_CHECK_PERSISTENCE_FAILED"

    WRITER_INPUT_INVALID = "WRITER_INPUT_INVALID"
    WRITER_GENERATION_FAILED = "WRITER_GENERATION_FAILED"
    WRITER_PERSISTENCE_FAILED = "WRITER_PERSISTENCE_FAILED"

    DATABASE_OPERATION_FAILED = "DATABASE_OPERATION_FAILED"

    WORKFLOW_EXECUTION_FAILED = "WORKFLOW_EXECUTION_FAILED"
